AWSTemplateFormatVersion: "2010-09-09"
Description: Test CF template that executes HTTP request using Custom::HttpRequestFunction lambda resource and outputs values from JSON response for each key in JsonHttpResponseKeyNames
Transform: 'AWS::LanguageExtensions'

Parameters:

  JsonHttpResponseKeyNames:
    Type: List<String>
    Description: List of key names in JSON response (Output will contain all key values)
    Default: one, key
    
Resources: 
 
  GetHttpRequestFunctionMultipleKeysTest:
    Type: Custom::HttpRequestFunction
    Properties:
      ServiceToken: {'Fn::ImportValue': 'http-request-function-arn'}
      Region: !Ref "AWS::Region"
      UrlAddress: "http://echo.jsontest.com/key/value/one/two"
      HttpMethod: "GET"
             
Outputs:

 'Fn::ForEach::GetAttLoop':
    - JsonKey
    - !Ref JsonHttpResponseKeyNames
    - ${JsonKey}:
        Export:
          Name: !Sub ${AWS::StackName}-${JsonKey}
        Value: !GetAtt ['GetHttpRequestFunctionMultipleKeysTest', !Ref JsonKey]